namespace Breezy.Core.Caching;

public static class CacheableInterface
{
	public const string Name = $"ICacheableQuery";
		
    public const string FullName = $"{BreezyGenerator.Namespace}.{Name}";
    
    public const string Content = $$"""
		// <auto-generated />
		using System;

		namespace {{BreezyGenerator.Namespace}};

		public interface {{Name}}<T> where T : class
		{
			public Task<IEnumerable<T>> GetCacheableResultsAsync(IdentityQuery identityQuery);
			public Task SetCacheableResultsAsync(IdentityQuery identityQuery, IEnumerable<T> results);
		}	
		""";
}