namespace Breezy.Core.IO.Attributes;

public static class TableAttribute
{
    public const string ShortName = "Table";

    public const string Name = $"{ShortName}Attribute";
		
    public const string FullName = $"{BreezyGenerator.Namespace}.{Name}";
    
    public const string Content = $$"""
		// <auto-generated />
		using System;

		namespace {{BreezyGenerator.Namespace}};

		[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
		public sealed class {{Name}} : Attribute
		{
			public string Name { get; init; }

			public {{Name}}(string name) => Name = name ?? throw new ArgumentNullException(name); 
		}
		""";
}